AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*
    - config/initializers/econfig.rb
    - config/initializers/devise.rb
    - config/initializers/rack-attack.rb
    - node_modules/**/*
    - spec/support/pusher-fake.rb
    - spec/support/matchers/has_react_component.rb
    - vendor/**/*
    - bin/*

Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:

Metrics/CyclomaticComplexity:
  Exclude:

Metrics/LineLength:
  Max: 120
  Exclude:

Metrics/MethodLength:
  Max: 30
  Exclude:

Metrics/ModuleLength:
  Max: 200
  Exclude:

Metrics/ParameterLists:
  Exclude:

Metrics/PerceivedComplexity:
  Exclude:

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
